== Introduction

{app-name} is a powerful test automation framework for mobile wireless testbeds.
The framework provides a flexible solution to instantiate complete networks
and run a very broad range of tests on testbeds comprising mixtures of
general-purpose SDR hardware, dedicated mobile wireless infrastructure equipment,
COTS UE devices and commercial test equipment.

{app-name} runs on a host PC (the `main unit') as a Python process. This
main unit process may orchestrate remote processes on `slave unit' PCs connected
to the main unit, usually over SSH. Hardware devices (e.g. SDRs, modems, channel
emulators, etc) connected to either the main unit or slaves units are controlled
via IP, raw ethernet, USB or similar means·

In {app-name}, a _resource_ is the name given to a hardware device or combination
of PC and device. Each _resource_ has a different physical setup, configuration,
supported features, attributes, etc. _Resources_ are instances of a _resource class_
such as a `UE' or an `eNodeB'. For example, an {app-name} setup may have 2 `UE'
instances and 1 `eNodeB' instance. Each of
these _resources_ are listed and described in configuration files passed to
{app-name}, which maintains a pool of _resources_ (available, in use, etc.).

Where SDR applications (such as srsUE or srsENB) are being tested, {app-name}
typically uses a pre-built binary package of the applications (a _trial_). To run tests {app-name}
launches one or more test _suites_, each containing a set of test scripts.
These tests use APIs provided by {app-name} to configure,
launch and manage the different applications from the _trial_ binary
package. Together with a set of _resources_, {app-name} can orchestrate
a complete network and run tests upon it.

Test _suites_ also contain configuration files to specify the resources
required to run its tests. They provide ways to filter which kind of
_resources_ will be needed based on their attributes. This permits, for instance,
asking {app-name} to provide a `UE' supporting 4G, or to provide a specific
type of `eNodeB' such as srsENB with USRP B210 SDR front-end. Test _suites_ also
support _scenarios_, which can act as additional filters on specified resources and
as modifiers which can overwrite some of the configuration values of different _resources_
or of {app-name} itself.

In many cases, one may want to run the same test suite several times, each with
different set of _resources_. For instance, one may want to run a test suite with
an Amarisoft eNodeB and later with an srsENB eNodeB. This is supported by leaving
the test suite configuration generic enough and then passing one or more _scenarios_
to it, which allow applying extra filters or modifiers. Multiple _scenarios_ can also be combined to
filter further or to apply further modifications.

.Sample 4G setup
[graphviz]
----
digraph G {
	rankdir=LR;
	jenkins
	subgraph cluster_sdr_hardware {
		label = "SDR Hardware";
		style=dotted

		B200 [label="Ettus B200" shape=box]
		B200_mini [label="Ettus B200_mini" shape=box]
		rf_distribution [label="RF distribution"]

		{B200 B200_mini}->rf_distribution [dir=both arrowhead="curve" arrowtail="curve"]
	}
	subgraph cluster_slave_unit1 {
	  label = "Slave Unit 1"
	  srsue [label="srsUE"]
	  srsepc [label="srsEPC"]
	}
	subgraph cluster_slave_unit2 {
	  label = "Slave Unit 2"
	  srsenb [label="srsENB"]
	}
	subgraph cluster_main_unit {
	  label = "Main Unit"
	  osmo_gsm_tester [label="Osmo-GSM-Tester\ntest suites\n& scenarios"]
	  subgraph {
		rank=same
		srsepc [label="srsEPC"]
	  }
	}

	jenkins->osmo_gsm_tester [label="trial\n(binaries)"]
	osmo_gsm_tester->jenkins [label="results"]
	osmo_gsm_tester->{srsue, srsenb, srsepc} [taillabel="SSH"]
	srsenb->B200 [label="UHD/USB"]
	srsue->B200_mini [label="UHD/USB"]
	srsenb->srsepc [dir=both label="GTP"]
}
----
