== Running Osmo-GSM-Tester

=== State Directory

Osmo-GSM-Tester uses a single directory to hold global or system-wide state.
In a typical state directory you can find the following files:

'last_used_*.state'::
	Contains stateful content spanning across Osmo-GSM-Tester instances and
	runs. For instance, 'last used msisdn number.state' is automatically
	(and atomically) increased every time Osmo-GSM-Tester needs to assign a
	new subscriber in a test, ensuring tests get unique msisdn numbers.
'reserved_resources.state'::
	File containing a set of reserved resources by any number of
	Osmo-GSM-Tester instances (aka pool of allocated resources). Each
	Osmo-GSM-Tester instance is responsible to clear its resources from the
	list once it is done using them and are no longer reserved.
'lock'::
	Lock file used to implement a mutual exclusion zone around any state
	files in the 'state_dir', to prevent race conditions between different
	Osmo-GSM-Tester instances running in parallel.

This way, several concurrent users of Osmo-GSM-Tester (ie. several
Osmo-GSM-Tester processes running in parallel) can run without interfering with
each other (e.g. using same ARFCN, same IP or same physical resources).

If you would like to set up several separate configurations (not typical), note
that the 'state_dir' is used to reserve resources, which only works when all
configurations that share resources also use the same 'state_dir'. It's also
important to note that since resources are stored in YAML dictionary form, if
the same physical device is described differently in several
<<resource_conf,resources.conf>> files (used by different Osmo-GSM-Tester instances),
resource allocation may not work as expected.

=== Config Paths

Osmo-GSM-Tester looks for configuration files in various standard
directories in this order:

- '$HOME/.config/osmo-gsm-tester/'
- '/usr/local/etc/osmo-gsm-tester/'
- '/etc/osmo-gsm-tester/'

The config location can also be set by an environment variable
'$OSMO_GSM_TESTER_CONF', which then overrides the above locations.

Osmo-GSM-Tester expects to find the following configuration files in a
configuration directory:

- paths.conf
- resources.conf
- default-suites.conf (optional)
- defaults.conf (optional)


The 'paths.conf' file specifies the locations of test suites, scenario definitions
and the state directory, used to store the global state:
----
state_dir: '/var/tmp/osmo-gsm-tester/state'
suites_dir: './suites'
scenarios_dir: './scenarios'
----
Any relative paths found in a 'paths.conf' file are interpreted as relative to
the directory of that 'paths.conf' file.


The 'resources.conf' file lists available resources as described in the previous section.

The optional 'default-suites.conf' file contains a YAML list of 'suite:scenario' combinations.
If Osmo-GSM-Tester is invoked without suite definitions, this default list is used. Each
'suite:scenario' combination is run in sequence. A suite name must match the name of a directory in the
suites_dir as defined by paths.conf. A scenario name must match the name of a configuration file in the
scnearios_dir as defined by paths.conf (optionally without the '.conf' suffix).

The optional 'defaults.conf' file contains a set of
default attributes and values (in YAML format) that object classes can use by default
if these are not specified in the 'resources.conf' file. These can easily be changed or
overwritten by suite.conf or scenario.conf files through modifiers.

Each binary run by osmo-gsm-tester, e.g. 'srsue' or 'srsenb',
typically has a configuration file template that is populated with values for a
trial run. Hence, a suite.conf, scenario.conf
or a resources.conf providing a similar setting always has
precedence over the values given in a 'defaults.conf'

=== Execution

Each invocation of Osmo-GSM-Tester runs a _suite_ of tests using
precompiled binary applications from a _trial_ with specified _resources_
which are selected and configured using _scenarios_.

Examples for launching tests:

- Run the default suites (see <<default_suites_conf,default_suites.conf>>) on a
  given set of binaries:

----
osmo-gsm-tester.py path/to/my-trial
----

- Run an explicit choice of 'suite:scenario':

----
osmo-gsm-tester.py path/to/my-trial -s 4g:srsenb@UHD,6
----

- Run one 'suite:scenario1+scenario2' combination, setting log level to 'debug'
  and enabling logging of full python tracebacks, and also only run just the
  'ping.py' test from the suite:

----
osmo-gsm-tester.py path/to/my-trial -s 4g:srsenb@UHD,6+srsue@UHD -l dbg -T -t ping
----

A test script may also be run step-by-step in a python debugger, see
<<debugging>>.
